### ISSUE TITLE
How to install multiple crates?

### ISSUE THREAD

**Issue by jarmos-san** [extractions/setup-crate#3]
I would like to install both `mdbook` & the `mdbook-mermaid` plugin crates. Is it possible to install both of these together using this Action?

**Comment by rossmacarthur** [comment]
No, currently you have to run the action twice

```yaml
- uses: extractions/setup-crate@v1
  with:
    owner: rust-lang
    name: mdBook

- uses: extractions/setup-crate@v1
  with:
    owner: badboy
    name: mdbook-mermaid
```
